name: Build

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt update && sudo apt -y install gcc-arm-none-eabi libmpc-dev

    - name: Build newlib
      run: ./build-newlib

    - name: Build libstdc++
      run: ./build-libstdc++

    - name: Package
      if: github.event_name == 'release'
      shell: bash
      run: 7z a stdlibs.zip no-pic pic

    - name: Upload
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: ./stdlibs.zip
