name: Build

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt -y install gcc-arm-none-eabi libmpc-dev

    - name: Build newlib
      run: ./build-newlib

    - name: Build libstdc++
      run: ./build-libstdc++